import type { Metadata } from 'next'
import { Rubik } from 'next/font/google'
import './globals.css'
import Providers from '@/providers/Providers'

const rubik = Rubik({
    subsets: ['latin'],
    variable: '--font-rubik',
})
export const metadata: Metadata = {
    title: 'Dokidoki',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang='en'>
            <body className={`${rubik.className} antialiased`}>
                <Providers>{children}</Providers>
            </body>
        </html>
    )
}
